### ISSUE TITLE
Adding require macro

### ISSUE THREAD

**Issue by kehiy** [0keeper1/nanotest#4]
Assert only checks the condition and goes ahead and runs all tests. but sometimes if function A doesn't work, then the rest of the tests will fail and we are sure about that.

We have to define `require` here. Example:

```c
NANO_REQUIRE_GE_INT( TESTNAME, expected, actual );
```

> Or maybe add a required field to asserts?

If the condition of these macros was false, then we will panic and halt. So, we won't wait a lot for tests that we are sure they will fail. it's very useful in pipelines and ...

**Comment by 0keeper1** [comment]
Doing this and creating duplicate Macros just for panic is not a good idea it's just more macros definition, panic or do not panic if failed can be an option in macros.
